#page title
page_title                                : Discover the benefits of cold showers | Cryo - Cold Shower App (available on iOS) # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1632354353                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Cryo                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Unlock the benefit of cold shower therapy for your body by making them a part of your daily routine with Cryo. Inspired by Wim Hof's "Becoming the Iceman".

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Team Cryo
your_link                                 : https://getcryo.app
your_city                                 : New York, NY
email_address                             : getcryoapp@gmail.com
facebook_username                         :
instagram_username                        : GetCryo
twitter_username                          : GetCryo
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Smart timer for cold/warm sessions
    description                           : A cold shower session starts with a warm shower, followed by a cold shower. The guided session will gradually increase the length of the cold shower timer.
    fontawesome_icon_name                 : clock
    
  - title                                 : Reduced stress levels
    description                           : Regularly taking cold showers trains your nervous system to become more resilient.
    fontawesome_icon_name                 : brain

  - title                                 : Stronger immune system
    description                           : Research shows that cold showers increase the number of white blood cells in your body, which protect your body against diseases.
    fontawesome_icon_name                 : first-aid

  - title                                 : Weight loss
    description                           : Cold showers increase your metabolic rate and are an effective method to help you get lean.
    fontawesome_icon_name                 : weight

  - title                                 : Improved sexual health
    description                           : Prolonged exposure to cold water has also been shown to increase testosterone production, boosting the libido and enhancing overall strength and energy in the process.
    fontawesome_icon_name                 : heart

  - title                                 : Increased willpower
    description                           : Cold showers are an effective and safe way to learn how to become comfortable with being uncomfortable.
    fontawesome_icon_name                 : bolt

  - title                                 : Faster muscle recovery
    description                           : Research found that cold water immersion can help enhance recovery and reduce feelings of fatigue for athletes.
    fontawesome_icon_name                 : dumbbell

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#219AFE"
topbar_transparency                       : 0
topbar_title_color                        : "#ffffff"

cover_image                               : # assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#219AFE"
cover_overlay_transparency                : 1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
